version: '3.4'

services:
  web:
    build:
      context: .
      target: development
    depends_on:
      - css
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - APP_DATA_PATH=/app/db/development.sqlite3
      - STORAGE_MODE=local
    stop_grace_period: "3s"
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      - litestream_data:/data

  css:
    command: "bin/yarn build:css --watch"
    build:
      context: .
      target: development
    environment:
      - STORAGE_MODE=local
    tty: true
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle

  test:
    build:
      context: .
      target: development
    environment:
      - RAILS_ENV=test
      - STORAGE_MODE=local
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle

volumes:
  bundle:
  litestream_data:
