version: '3.4'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  bundle:
  postgresql:
