version: '3.4'

services:
  web:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      - litestream_data:/data

  test:
    build:
      context: .
      target: development
    environment:
      - RAILS_ENV=test
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle

volumes:
  bundle:
  litestream_data:
