default: &default
  encoding: utf8
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
