default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password: secret
  pool: 5

development:
  <<: *default
  database: wednesdayworlds

test:
  <<: *default
  database: wednesdayworlds_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
