name: Build

on: [push]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Copy .env
      run: cp .env-sample .env

    - name: Setup /tmp dirs
      run: sudo mkdir -p ./tmp/cache

    - name: Build & start containers
      run: docker-compose up -d --build

    - name: Run RSpec examples
      run: docker-compose run --rm web bundle exec rspec

    - name: Stop containers
      if: always()
      run: docker-compose down
